version: '3'
services:

  build:
    entrypoint: pip install
    image: lambci/lambda:build-python3.7
    volumes:
      - ./build:/var/task

  package:
    command: zip -x '*__pycache__/*' '*.dist-info/*' -r - .
    image: lambci/lambda:build-python3.7
    volumes:
      - ./build:/var/task
