version: "3.8"
volumes:
  root:
services:
  build:
    build:
      context: .
      target: build
    image: amancevice/facebook-gcal-sync:build

  test:
    build: .
    env_file: .env
    image: amancevice/facebook-gcal-sync:test
    ports:
      - 8080
