version: '3.8'
volumes:
  root:
services:

  base: &base
    build: .
    image: ${REPO:-amancevice/facebook-gcal-sync}
    network_mode: bridge

  shell: &shell
    <<: *base
    command: bash
    entrypoint: env
    env_file: .env
    volumes:
      - root:/root
      - ~/.aws:/root/.aws:ro
      - ./:/var/task

  lambda:
    <<: *base
    ports:
      - 8080
