version: '3'
services:
  package:
    command: >
      sh -c "
        rm -rf build/* &&
        pip install fest==5.0.0a6 -t build &&
        cp lambda.py build &&
        cd build &&
        zip -x '*.pyc' '*__pycache__/*' -r ../package.zip ./*
      "
    image: lambci/lambda:build-python3.7
    volumes:
      - ./:/var/task
      - ./build:/var/task/build
