name: validate
on:
  pull_request:
  push:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: hashicorp/setup-terraform@v1
      - run: pip install pipenv==2022.1.8
      - run: make
